import json
from groq import Groq
from config import GROQ_API_KEY, LLM_MODEL

_client = Groq(api_key=GROQ_API_KEY)

_SYSTEM_PROMPT = """\
You are an expert at detecting AI-generated versus human-written text.
Analyze the following text and determine whether it was likely written by a human or generated by an AI.

Consider these characteristics:
- Tone consistency and predictability
- Sentence structure variation
- Presence of natural inconsistencies (humans are messier)
- Clichés and stock transitions
- Narrative flow and authenticity
- Presence of unique phrasing vs. generic language

OUTPUT FORMAT
Respond with a JSON object (and ONLY the JSON, no other text) containing:
{{
  "label": "ai" or "human",
  "confidence": <0.0-1.0 representing your certainty in the label>,
  "reasoning": "<one-sentence justification>"
}}
Where confidence is your certainty in YOUR CHOSEN LABEL (not a binary probability).
"""

_USER_PROMPT = "Classify this text: \n\n{text}"

def signal_1_llm_attribution(text: str) -> dict:
    """
    Signal 1: LLM-based attribution assessment using Groq Llama 3.3 70B.
    
    Args:
        text: The text to analyze
    
    Returns:
        dict with:
          - llm_score: normalized score on [0, 1]
          - label: "ai", "human", or "uncertain"
          - confidence: model's confidence in its own label
          - reasoning: brief explanation
    """
    try:
        response = _client.chat.completions.create(
            model=LLM_MODEL,
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": _USER_PROMPT.format(text=text)}
            ],
            temperature=0.0,  # Deterministic
            max_tokens=200,
        )
        
        # Extract JSON from response
        response_text = response.choices[0].message.content.strip()
        parsed = json.loads(response_text)
        
        # Normalize to shared scale: label + confidence → llm_score
        label = parsed["label"].lower()
        label_confidence = parsed["confidence"]
        
        if label == "ai":
            llm_score = label_confidence
        elif label == "human":
            llm_score = 1 - label_confidence
        else:
            llm_score = 0.5  # Fallback to uncertain
        
        return {
            "llm_score": llm_score,
            "label": label,
            "confidence": label_confidence,
            "reasoning": parsed["reasoning"]
        }
    
    except json.JSONDecodeError as e:
        print(f"JSON parse error: {e}")
        print(f"Raw response: {response_text}")
        return {
            "llm_score": 0.5,
            "label": "uncertain",
            "confidence": 0.5,
            "reasoning": "Error parsing model response"
        }
    except Exception as e:
        print(f"Error calling Groq API: {e}")
        return {
            "llm_score": 0.5,
            "label": "uncertain",
            "confidence": 0.5,
            "reasoning": f"API error: {str(e)}"
        }


if __name__ == "__main__":
    # Test the signal independently
    test_cases = [
        {
            "name": "Clearly AI-generated",
            "text": """Artificial intelligence represents a transformative paradigm shift in modern society. 
It is important to note that while the benefits of AI are numerous, it is equally 
essential to consider the ethical implications. Furthermore, stakeholders across 
various sectors must collaborate to ensure responsible deployment."""
        },
        {
            "name": "Clearly human-written",
            "text": """ok so i finally tried that new ramen place downtown and honestly? 
underwhelming. the broth was fine but they put WAY too much sodium in it and 
i was thirsty for like three hours after. my friend got the spicy version and 
said it was better. probably won't go back unless someone drags me there"""
        },
        {
            "name": "Formal human writing",
            "text": """The relationship between monetary policy and asset price inflation has been 
extensively studied in the literature. Central banks face a fundamental tension 
between their mandate for price stability and the unintended consequences of 
prolonged low interest rates on equity and real estate valuations."""
        },
        {
            "name": "Lightly edited AI output",
            "text": """I've been thinking a lot about remote work lately. There are genuine tradeoffs — 
flexibility and no commute on one side, isolation and blurred work-life boundaries 
on the other. Studies show productivity varies widely by individual and role type."""
        }
    ]
    
    print("=" * 80)
    print("TESTING SIGNAL 1: LLM ATTRIBUTION")
    print("=" * 80)
    
    for test in test_cases:
        print(f"\n[{test['name']}]")
        print(f"Text preview: {test['text'][:80]}...")
        result = signal_1_llm_attribution(test["text"])
        print(f"  llm_score: {result['llm_score']:.3f}")
        print(f"  label: {result['label']}")
        print(f"  confidence: {result['confidence']:.3f}")
        print(f"  reasoning: {result['reasoning']}")
