import json
import math
import re
from groq import Groq
from config import GROQ_API_KEY, LLM_MODEL
from collections import Counter
from itertools import combinations


_client = Groq(api_key=GROQ_API_KEY)

_SYSTEM_PROMPT = """You are an expert at detecting AI-generated versus human-written text.
Analyze the following text and determine whether it was likely written by a human or generated by an AI.

Consider these characteristics:
- Tone consistency and predictability
- Sentence structure variation
- Presence of natural inconsistencies (humans are messier)
- Clichés and stock transitions
- Narrative flow and authenticity
- Presence of unique phrasing vs. generic language

OUTPUT FORMAT
Respond with a JSON object (and ONLY the JSON, no other text) containing:
{{
  "label": "ai" or "human",
  "confidence": <0.0-1.0 representing your certainty in the label>,
  "reasoning": "<one-sentence justification>"
}}
Where confidence is your certainty in YOUR CHOSEN LABEL (not a binary probability).
"""

_USER_PROMPT = "Classify this text: \n\n{text}"

STOCK_TRANSITIONS = [
    "however",
    "moreover",
    "furthermore",
    "therefore",
    "thus",
    "in conclusion",
    "overall",
    "it is important to note",
    "it is worth noting",
    "on the other hand",
    "in summary",
    "as a result",
    "for example",
    "for instance",
    "ultimately",
    "in today's world",
    "plays a crucial role",
    "delve",
    "tapestry",
]


def _clamp(value: float, min_value: float = 0.0, max_value: float = 1.0) -> float:
    return max(min_value, min(max_value, value))


def _word_tokens(text: str) -> list[str]:
    return re.findall(r"\w+", text.lower())


def _split_sentences(text: str) -> list[str]:
    return [s.strip() for s in re.split(r'(?<=[.!?])\s+|\n+', text) if s.strip()]


def _prefix_repetition(sentences: list[str]) -> float:
    prefixes = []

    for sentence in sentences:
        words = _word_tokens(sentence)
        if len(words) >= 3:
            prefixes.append(words[:3])
        elif words:
            prefixes.append(words)

    if len(prefixes) < 2:
        return 0.0

    similarity = 0.0
    comparisons = 0

    for a, b in combinations(prefixes, 2):
        matches = sum(x == y for x, y in zip(a, b))
        similarity += matches / max(len(a), len(b))
        comparisons += 1

    return similarity / comparisons


def _bigram_repetition(tokens: list[str]) -> float:
    if len(tokens) < 4:
        return 0.0

    bigrams = [
        tuple(tokens[i:i+2])
        for i in range(len(tokens)-1)
    ]

    counts = Counter(bigrams)

    duplicates = sum(count - 1 for count in counts.values() if count > 1)

    return duplicates / len(bigrams)


def _sentence_length_variance_score(text: str) -> float:
    sentences = _split_sentences(text)
    lengths = [len(_word_tokens(sentence)) for sentence in sentences if _word_tokens(sentence)]
    if len(lengths) < 3:
        return 0.5

    mean = sum(lengths) / len(lengths)
    variance = sum((length - mean) ** 2 for length in lengths) / len(lengths)
    cv = math.sqrt(variance) / mean if mean else 0.0

    # Very low sentence-length CV is more AI-like, but only fairly strongly
    # below ~0.30. Text with too few sentences is not reliable.
    score = (0.45 - cv) / 0.25
    return _clamp(score)


def _mattr_score(text: str, window: int = 50) -> float:
    tokens = _word_tokens(text)

    if len(tokens) < window:
        return 0.5

    ttrs = []

    for i in range(len(tokens) - window + 1):
        chunk = tokens[i:i + window]
        ttrs.append(len(set(chunk)) / window)

    mattr = sum(ttrs) / len(ttrs)

    # Lower MATTR → more AI-like
    score = (0.80 - mattr) / (0.80 - 0.55)

    return _clamp(score)


def _punctuation_entropy_score(text: str) -> float:
    punctuation_chars = [c for c in text if c in ".,;:—!?()[]{}"]
    if not punctuation_chars:
        return 0.5

    counts = {}
    for char in punctuation_chars:
        counts[char] = counts.get(char, 0) + 1

    total = len(punctuation_chars)
    entropy = -sum((count / total) * math.log2(count / total) for count in counts.values())

    # High entropy means lots of punctuation variety, which is more human-like.
    # Low entropy means repetition of just one or two marks, which is more AI-like.
    score = (1.2 - entropy) / 0.7
    return _clamp(score)

def _discourse_repetition_score(text: str) -> float:
    sentences = _split_sentences(text)
    tokens = _word_tokens(text)

    prefix_rep = _prefix_repetition(sentences)
    bigram_rep = _bigram_repetition(tokens)

    repetition_rate = (
        0.5 * prefix_rep +
        0.5 * bigram_rep
    )

    score = repetition_rate / 0.35

    return _clamp(score)


def _stock_transition_score(text: str) -> float:
    text_lower = text.lower()
    word_count = max(len(_word_tokens(text)), 1)

    matches = 0
    for phrase in STOCK_TRANSITIONS:
        matches += text_lower.count(phrase)

    density = matches / word_count * 100

    # ≥2 phrases per 100 words → maximally AI-like
    score = density / 2.0

    return _clamp(score)


def signal_2_stylometry(text: str) -> dict:
    """
    Signal 2: Stylometry heuristics using sentence length variance, type-token ratio,
    and punctuation entropy.

    Returns a dictionary with a combined stylometry_score and sub-scores.
    """
    sentence_variance = _sentence_length_variance_score(text)
    lexical_diversity = _mattr_score(text)
    punctuation_entropy = _punctuation_entropy_score(text)
    discourse_repetition = _discourse_repetition_score(text)
    stock_transition_density = _stock_transition_score(text)

    stylometry_score = (
        0.20 * sentence_variance +
        0.15 * discourse_repetition +
        0.25 * lexical_diversity +
        0.20 * punctuation_entropy +
        0.20 * stock_transition_density
    )

    return {
        "stylometry_score": stylometry_score,
        "sentence_variance": sentence_variance,
        "lexical_diversity": lexical_diversity,
        "punctuation_entropy": punctuation_entropy,
        "discourse_repetition": discourse_repetition,
        "stock_transition_density": stock_transition_density
    }


def combine_signal_scores(llm_score: float, stylometry_score: float, w_llm: float = 0.6, w_sty: float = 0.4, shrinkage_lambda: float = 0.5) -> float:
    p_raw = w_llm * llm_score + w_sty * stylometry_score
    disagreement = abs(llm_score - stylometry_score)
    p_ai = 0.5 + (p_raw - 0.5) * (1 - shrinkage_lambda * disagreement)
    return _clamp(p_ai)


def classify_score(p_ai: float) -> tuple[str, float]:
    if p_ai >= 0.65:
        return "likely_ai", p_ai
    if p_ai <= 0.35:
        return "likely_human", 1 - p_ai
    return "uncertain", max(p_ai, 1 - p_ai)


def signal_1_llm_attribution(text: str) -> dict:
    """
    Signal 1: LLM-based attribution assessment using Groq Llama 3.3 70B.
    
    Args:
        text: The text to analyze
    
    Returns:
        dict with:
          - llm_score: normalized score on [0, 1]
          - label: "ai", "human", or "uncertain"
          - confidence: model's confidence in its own label
          - reasoning: brief explanation
    """
    try:
        response = _client.chat.completions.create(
            model=LLM_MODEL,
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": _USER_PROMPT.format(text=text)}
            ],
            temperature=0.0,  # Deterministic
            max_tokens=200,
        )
        
        # Extract JSON from response
        response_text = response.choices[0].message.content.strip()
        parsed = json.loads(response_text)
        
        # Normalize to shared scale: label + confidence → llm_score
        label = parsed["label"].lower()
        label_confidence = parsed["confidence"]
        
        if label == "ai":
            llm_score = label_confidence
        elif label == "human":
            llm_score = 1 - label_confidence
        else:
            llm_score = 0.5  # Fallback to uncertain
        
        return {
            "llm_score": llm_score,
            "label": label,
            "confidence": label_confidence,
            "reasoning": parsed["reasoning"]
        }
    
    except json.JSONDecodeError as e:
        print(f"JSON parse error: {e}")
        print(f"Raw response: {response_text}")
        return {
            "llm_score": 0.5,
            "label": "uncertain",
            "confidence": 0.5,
            "reasoning": "Error parsing model response"
        }
    except Exception as e:
        print(f"Error calling Groq API: {e}")
        return {
            "llm_score": 0.5,
            "label": "uncertain",
            "confidence": 0.5,
            "reasoning": f"API error: {str(e)}"
        }


if __name__ == "__main__":
    # Test the signal independently
    test_cases = [
        {
            "name": "Clearly AI-generated",
            "text": """Artificial intelligence represents a transformative paradigm shift in modern society. 
It is important to note that while the benefits of AI are numerous, it is equally 
essential to consider the ethical implications. Furthermore, stakeholders across 
various sectors must collaborate to ensure responsible deployment."""
        },
        {
            "name": "Clearly human-written",
            "text": """ok so i finally tried that new ramen place downtown and honestly? 
underwhelming. the broth was fine but they put WAY too much sodium in it and 
i was thirsty for like three hours after. my friend got the spicy version and 
said it was better. probably won't go back unless someone drags me there"""
        },
        {
            "name": "Formal human writing",
            "text": """The relationship between monetary policy and asset price inflation has been 
extensively studied in the literature. Central banks face a fundamental tension 
between their mandate for price stability and the unintended consequences of 
prolonged low interest rates on equity and real estate valuations."""
        },
        {
            "name": "Lightly edited AI output",
            "text": """I've been thinking a lot about remote work lately. There are genuine tradeoffs — 
flexibility and no commute on one side, isolation and blurred work-life boundaries 
on the other. Studies show productivity varies widely by individual and role type."""
        }
    ]
    
    print("=" * 80)
    print("TESTING SIGNALS: LLM ATTRIBUTION + STYLOMETRY")
    print("=" * 80)
    
    for test in test_cases:
        print(f"\n[{test['name']}]")
        print(f"Text preview: {test['text'][:80]}...")
        result = signal_1_llm_attribution(test["text"])
        print(f"  llm_score: {result['llm_score']:.3f}")
        print(f"    label: {result['label']}")
        print(f"    confidence: {result['confidence']:.3f}")
        print(f"    reasoning: {result['reasoning']}")

        stylometry = signal_2_stylometry(test["text"])
        print(f"  stylometry_score: {stylometry['stylometry_score']:.3f}")
        print(f"    sentence_variance: {stylometry['sentence_variance']:.3f}")
        print(f"    discourse_repetition: {stylometry['discourse_repetition']:.3f}")
        print(f"    lexical_diversity: {stylometry['lexical_diversity']:.3f}")
        print(f"    punctuation_entropy: {stylometry['punctuation_entropy']:.3f}")
        print(f"    stock_transition_density: {stylometry['stock_transition_density']:.3f}")

        combined = combine_signal_scores(result["llm_score"], stylometry["stylometry_score"])
        classification, display_confidence = classify_score(combined)
        print(f"  combined p_ai: {combined:.3f}")
        print(f"  final_classification: {classification}")
        print(f"  final_confidence: {display_confidence:.3f}")
